/**
 * GLSL ES 3.00 shader sources for the Big Bang satellite.
 *
 * The simulation keeps particle coordinates in comoving/local space.
 * RENDER_VERTEX applies the global background scale factor a(t) exactly once.
 *
 * This remains a stylized visualization rather than a scientific cosmological
 * solver. The purpose of the decomposition is to keep global expansion and
 * local structure formation semantically separate.
 */

/* ---- Simulation pass (transform feedback; no fragment output) ---- */

export const SIM_VERTEX = /* glsl */ `#version 300 es
precision highp float;

layout(location = 0) in vec3 a_position;
layout(location = 1) in vec3 a_velocity;
layout(location = 2) in vec3 a_seed;
layout(location = 3) in vec3 a_dir;

uniform float u_time;   // normalized [0,1)
uniform float u_dt;     // effective simulation delta

out vec3 v_position;
out vec3 v_velocity;

// Smooth phase weight peaking inside [a,b] via overlapping smoothsteps.
float band(float t, float a, float b, float fade) {
  float lo = smoothstep(a - fade, a + fade, t);
  float hi = 1.0 - smoothstep(b - fade, b + fade, t);
  return clamp(min(lo, hi), 0.0, 1.0);
}

void main() {
  float t = clamp(u_time, 0.0, 1.0);

  /*
   * Phase boundaries mirror simulation.ts PHASES exactly:
   *
   * singularity  0.00
   * inflation    0.08
   * expansion    0.30
   * cooling      0.58
   * structure    0.80
   *
   * PHASES remains the authoritative CPU definition; these literals are the
   * corresponding GLSL implementation of the same lifecycle intervals.
   */
  float wSingularity = 1.0 - smoothstep(0.0, 0.08, t);
  float wInflation   = band(t, 0.08, 0.30, 0.04);
  float wExpansion   = band(t, 0.30, 0.58, 0.05);
  float wCooling     = band(t, 0.58, 0.80, 0.06);
  float wStructure   = smoothstep(0.80, 0.92, t);

  // The stored state is comoving/local state, not globally expanded world state.
  vec3 pos = a_position;
  vec3 vel = a_velocity;

  /*
   * Keep the initial phase concentrated. There is intentionally no unconditional
   * frame-rate-dependent velocity damping: global damping was one of the old
   * mechanisms that made the late cloud freeze.
   *
   * The small singularity contribution here is a position-space constraint
   * rather than a global velocity multiplier.
   */
  float r = length(pos);
  if (r > 1e-5) {
    vec3 outward = pos / r;

    // A very small outward impulse lets the local field begin separating during
    // inflation; the dominant global expansion is supplied analytically by a(t)
    // in the render pass.
    vel += outward *
      (0.0035 * wInflation + 0.0010 * wExpansion) *
      u_dt;
  }

  /*
   * Cooling suppresses small-scale turbulent noise only. It does not suppress
   * the global scale factor, so the universe can keep expanding while becoming
   * visually colder and dynamically quieter.
   */
  float turbulence = (a_seed.x - 0.5) * 2.0;
  vec3 jitter =
    a_dir *
    turbulence *
    0.055 *
    (1.0 - wCooling);

  vel += jitter * u_dt;

  /*
   * Local comoving web field.
   *
   * a_dir is a deterministic shared structural orientation generated by
   * simulation.ts. Instead of attracting every particle toward a fixed global
   * target, particles are assigned deterministic local filament/node groups.
   * The force is computed from the particle's current comoving position.
   *
   * The discrete seed groups make neighboring particles reuse the same
   * filament manifolds and junctions, producing coherent filaments/nodes while
   * avoiding the old "everything collapses toward radius 0.6..1.1" behavior.
   */
  vec3 d = normalize(a_dir);

  // Stable orthonormal basis around the particle's structural direction.
  vec3 helper =
    abs(d.y) < 0.9
      ? vec3(0.0, 1.0, 0.0)
      : vec3(1.0, 0.0, 0.0);

  vec3 side = normalize(cross(d, helper));
  vec3 crossSide = normalize(cross(d, side));

  // Deterministic discrete local groups.
  float filamentGroup =
    floor(a_seed.y * 7.0) / 6.0 - 0.5;

  float transverseGroup =
    floor(a_seed.z * 5.0) / 4.0 - 0.5;

  float nodeGroup =
    floor(a_seed.x * 6.0) / 5.0 - 0.5;

  /*
   * Each group defines a local filament manifold parallel to d.
   * Different seed groups therefore populate multiple coherent filaments.
   */
  vec3 filamentOrigin =
    side * (filamentGroup * 0.52) +
    crossSide * (transverseGroup * 0.34);

  vec3 relativeToFilament = pos - filamentOrigin;
  float axialDistance = dot(relativeToFilament, d);
  vec3 nearestFilament =
    filamentOrigin + d * axialDistance;

  vec3 toFilament = nearestFilament - pos;

  /*
   * Nodes are points on/near the local filament. The node force has finite
   * influence, so distant particles are not globally pulled toward one center.
   */
  vec3 node =
    filamentOrigin +
    d * (nodeGroup * 0.72);

  vec3 toNode = node - pos;
  float nodeDistance = length(toNode);

  float nodeInfluence =
    1.0 - smoothstep(0.12, 0.58, nodeDistance);

  /*
   * Structure formation acts only on comoving coordinates and is intentionally
   * subordinate to the background scale factor applied by the render pass.
   */
  float filamentStrength = 0.48 * wStructure;
  float nodeStrength = 0.22 * wStructure * nodeInfluence;

  vel += toFilament * filamentStrength * u_dt;

  if (nodeDistance > 1e-5) {
    vel +=
      (toNode / nodeDistance) *
      nodeStrength *
      u_dt;
  }

  /*
   * Small late-time shear along the local filament keeps the web from becoming
   * a collection of motionless lines. It is comoving/local and remains bounded.
   */
  float shear =
    (a_seed.z - 0.5) *
    0.018 *
    wStructure;

  vel += d * shear * u_dt;

  /*
   * Integrate only local/comoving motion.
   *
   * There is deliberately:
   *   - no global vel *= 0.985 damping;
   *   - no hard maxR clamp;
   *   - no fixed-radius global target.
   *
   * Global expansion is applied exactly once in RENDER_VERTEX.
   */
  pos += vel * u_dt;

  v_position = pos;
  v_velocity = vel;

  gl_Position = vec4(0.0); // unused; rasterizer discard is on.
}
`;

// A no-op fragment shader is still required to link the transform-feedback
// simulation program.
export const SIM_FRAGMENT = /* glsl */ `#version 300 es
precision highp float;

out vec4 fragColor;

void main() {
  fragColor = vec4(0.0);
}
`;

/* ---- Render pass ---- */

export const RENDER_VERTEX = /* glsl */ `#version 300 es
precision highp float;

layout(location = 0) in vec3 a_position;
layout(location = 1) in vec3 a_velocity;
layout(location = 2) in vec3 a_seed;

uniform float u_time;
uniform float u_aspect;
uniform float u_pixelRatio;

out float v_temp;
out float v_seed;

/*
 * Global background scale factor a(t).
 *
 * This is intentionally:
 *   a'(t) >= 0
 *   a(0) = 1
 *   strong growth during inflation
 *   continued growth through expansion/cooling/structure
 *
 * The maximum is finite because this is a visual normalization, not an
 * unbounded numerical cosmology simulation. There is no per-particle radius
 * clamp in the simulation state.
 */
float scaleFactor(float t) {
  float inflation =
    smoothstep(0.08, 0.30, t);

  float late =
    smoothstep(0.30, 1.0, t);

  /*
   * The powered inflation term gives a visibly explosive increase without an
   * impulse that must subsequently be counteracted by damping.
   *
   * a(t): approximately 1 -> 4.5 during inflation, then -> 6.0 over the
   * remainder of the lifecycle.
   */
  float inflationGrowth =
    pow(inflation, 1.8);

  return
    1.0 +
    3.5 * inflationGrowth +
    1.5 * late;
}

void main() {
  float t = clamp(u_time, 0.0, 1.0);

  // Normalized temperature: hot early, cools over the lifecycle.
  float temp =
    1.0 - smoothstep(0.1, 0.85, t);

  v_temp = temp;
  v_seed = a_seed.z;

  /*
   * Apply the global background expansion exactly once.
   *
   * a_position remains a comoving/local coordinate maintained by SIM_VERTEX.
   * Structure formation therefore changes relative organization without being
   * able to cancel the global expansion.
   */
  float a = scaleFactor(t);

  vec3 p = a_position * a;

  // Simple perspective camera, gently orbiting.
  float angle = t * 0.6;
  float ca = cos(angle);
  float sa = sin(angle);

  vec3 rp = vec3(
    p.x * ca - p.z * sa,
    p.y,
    p.x * sa + p.z * ca
  );

  float camDist = 3.2;
  vec3 eye = vec3(0.0, 0.0, camDist);
  vec3 view = rp - eye;

  float fov = 1.2;
  float f = 1.0 / tan(fov * 0.5);
  float near = 0.1;
  float far = 20.0;
  float z = view.z;

  vec4 clip;

  clip.x =
    view.x * f / u_aspect;

  clip.y =
    view.y * f;

  clip.z =
    (far + near) / (near - far) * z +
    (2.0 * far * near) / (near - far);

  clip.w = -z;

  gl_Position = clip;

  /*
   * Local velocity remains in comoving units. Keep its visual contribution
   * moderate because global scale is now the authoritative expansion signal.
   */
  float speed = length(a_velocity);

  float base =
    mix(1.5, 4.5, temp) +
    speed * 4.0;

  gl_PointSize = clamp(
    base *
    u_pixelRatio *
    (camDist / -z),
    1.0,
    40.0
  );
}
`;

export const RENDER_FRAGMENT = /* glsl */ `#version 300 es
precision highp float;

in float v_temp;
in float v_seed;

out vec4 fragColor;

void main() {
  vec2 c = gl_PointCoord - vec2(0.5);
  float d = length(c);

  if (d > 0.5) {
    discard;
  }

  // Soft luminous falloff.
  float glow =
    exp(-d * d * 7.0);

  // Hot -> blue-white; cool -> warm amber/red.
  vec3 hot =
    vec3(0.65, 0.8, 1.0);

  vec3 cool =
    vec3(1.0, 0.55, 0.28);

  vec3 color =
    mix(cool, hot, v_temp);

  // Subtle per-particle variance.
  color *=
    0.75 +
    v_seed * 0.4;

  float alpha =
    glow *
    mix(0.35, 0.9, v_temp);

  fragColor =
    vec4(color * alpha, alpha);
}
`;